#!/bin/bash
# usage recon-hippo <name of subject list file>
list=$1
IDP=/ifs/scratch/pimri/posnerlab/1anal/IDP

CMD1=/ifs/scratch/pimri/posnerlab/1anal/IDP/code/idp/job/job.hippo.${list}
rm -rf $CMD1

for s in `cat $IDP/data/$list`
do

SUBJECTS_DIR=/ifs/scratch/pimri/posnerlab/1anal/IDP/fs

IMPATH=/ifs/scratch/pimri/posnerlab/1anal/IDP/data/${s}
#FLAIR=`ls $IMPATH/flair*nii*`
#T1=`ls $IMPATH/t1*nii*`
SUBJECT=${s}_1mm_flair

recon1=/ifs/scratch/pimri/posnerlab/1anal/IDP/code/idp/job/hippo.${s}
rm -rf $recon1

cat<<EOC >$recon1
recon-all -hippocampal-subfields-T1 -s ${SUBJECT}
EOC

chmod +x $recon1



cat<<-EOM >>$CMD1
$recon1
EOM
done

#$code/fsl_sub_hpc_6 -t $CMD1
echo $CMD1
