#!/bin/bash
# usage recon-hippo <name of subject list file>
list=$1
IDP=/ifs/scratch/pimri/posnerlab/1anal/IDP

CMD1=/ifs/scratch/pimri/posnerlab/1anal/IDP/code/idp/job/job.hippo.left.${list}
CMD2=/ifs/scratch/pimri/posnerlab/1anal/IDP/code/idp/job/job.hippo.right.${list}

rm -rf $CMD1
rm -rf $CMD2

for s in `cat $IDP/data/$list`
do

SUBJECTS_DIR=/ifs/scratch/pimri/posnerlab/1anal/IDP/fs

IMPATH=/ifs/scratch/pimri/posnerlab/1anal/IDP/data/${s}
#FLAIR=`ls $IMPATH/flair*nii*`
#T1=`ls $IMPATH/t1*nii*`
SUBJECT=${s}_1mm_flair

cat<<EOM >>$CMD1
if [ ! -e $IDP/fs/${SUBJECT}/mri/lh.hippoSfVolumes-T1.v10.txt ] then
/ifs/home/msph/epi/jep2111/app/freesurfer//bin/segmentSF_T1.sh /ifs/home/msph/epi/jep2111/app/freesurfer//MCRv80 \
/ifs/home/msph/epi/jep2111/app/freesurfer/ ${SUBJECT} /ifs/scratch/pimri/posnerlab/1anal/IDP/fs left
fi
EOM

cat<<EOC >>$CMD2
if [ ! -e $IDP/fs/${SUBJECT}/mri/rh.hippoSfVolumes-T1.v10.txt ] then
/ifs/home/msph/epi/jep2111/app/freesurfer//bin/segmentSF_T1.sh /ifs/home/msph/epi/jep2111/app/freesurfer//MCRv80 \
/ifs/home/msph/epi/jep2111/app/freesurfer/ ${SUBJECT} /ifs/scratch/pimri/posnerlab/1anal/IDP/fs right
fi
EOC

#recon1=/ifs/scratch/pimri/posnerlab/1anal/IDP/code/idp/job/hippo.${s}
#rm -rf $recon1

#cat<<EOC >$recon1
#recon-all -hippocampal-subfields-T1 -s ${SUBJECT}
#EOC

#chmod +x $recon1



#cat<<-EOM >>$CMD1
#$recon1
#EOM
done

#$code/fsl_sub_hpc_12 -t $CMD1
echo $code/fsl_sub_hpc_12 -t $CMD2

#echo $CMD1
